### ISSUE TITLE
Ausence of some clustering/classification methods in weka 3.7

### ISSUE THREAD

**Issue by alfonsodelavega** [bnjmn/weka#2]
Hello,

I was tired of watching 10k+ warnings in the source of my weka 3.6 branch project all the time so I decided I wanted to do something about it, and I ended in your repo.

When downloading and compiling your mirror, I saw that weka 3.7 does not have some classification/clustering techniques which are included in 3.6, like Xmeans and half of the meta classifiers.

Do you have any idea why that happened? Did the authors include it in version 3.6 but left out the development version 3.7?

PS: Nice work cleaning the repo.

**Comment by bnjmn** [comment]
Hey! Thanks for stopping by. I'm glad you found something useful here. 

I'm not affiliated with the weka project in any official way and no longer keep up with the project. Wish I could help you with those questions but your guess and research is as good as mine. I've updated the repo today to mirror the source project; everything available should be included. Hope that helps!
