### ISSUE TITLE
README outdated with packages.html

### ISSUE THREAD

**Issue by heoa** [bnjmn/weka#7]
It reads that 

`c) Bookmark $WEKAINSTALL/doc/packages.html in your web browser.
`
but `packages.html` is removed. It should probably be 

`c) Bookmark $WEKAINSTALL/doc/index.html in your web browser.
`

**Comment by bnjmn** [comment]
Weka is not maintained here. This is just a mirror of the svn repository. If you'd like to get involved with the weka project directly, the project site is here http://www.cs.waikato.ac.nz/ml/index.html. Thanks for stopping by.
