### ISSUE TITLE
data format 

### ISSUE THREAD

**Issue by BayanIbra** [bnjmn/weka#9]
In what data format should I prepare my data to use LDA classifier with solver=svd. To identify the latent features ? Is it matrix format?

**Comment by bnjmn** [comment]
This repo is just a mirror of the weka project. No actual development goes on here. Please visit the [official github mirror](https://github.com/Waikato/weka-trunk) to find out more about how to contact the maintainers and, hopefully, solve your issue.

The main project site is here: http://www.cs.waikato.ac.nz/ml/weka/index.html
